name: Release

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  check:
    runs-on: ubuntu-24.04
    env:
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: earthbuild/actions-setup@cec13796de0f8178bfeed4ef3ea2e9d90d96fc7f # main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Bootstrap buildkitd
        run: earth bootstrap

      - name: Lint
        run: earth --ci +lint

      - name: Test
        run: earth --ci +test

  publish:
    needs: check
    if: github.event_name == 'pull_request' && startsWith(github.head_ref, 'release-v')
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: earthbuild/actions-setup@main
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      
      - name: Build Linux Bottles
        run: earth --ci +bottle-linux-all
        
      - name: Build macOS Bottle
        run: earth --ci +bottle-mac
        
      - name: Publish all Bottles
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          earth --ci \
            --secret GITHUB_TOKEN=$GITHUB_TOKEN \
            --build-arg GITHUB_REF=${{ github.head_ref }} \
            --build-arg GITHUB_SHA=${{ github.event.pull_request.head.sha }} \
            +publish
