name: Update Release Checksums

on:
  pull_request:
    branches:
      - 'release-v*'

permissions:
  contents: write

jobs:
  update-sha:
    runs-on: ubuntu-latest
    if: github.actor == 'renovate[bot]'
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Run checksum update script
        run: python3 scripts/update-checksums.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if ! git diff --exit-code Formula/earth.rb; then
            git add Formula/earth.rb
            git commit -m "chore: update sha256 checksums"
            git push
          else
            echo "No checksum changes detected."
          fi
